       <div class="row" id="panel2">
    <div class="container">
    
    <div class="navbar">
        <div class="container">
        <div class="visible-sm" id="collapseMenu">
        <span class="pull-left"><a href="tel:18888318303"><button type="button" class="btn btn-warning btn-default"><i class="icon-phone-sign icon-large"></i> Click to Call</button></a></span>
        <span id="menuText">Menu</span><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          </div>
          <div class="clearfix"></div>
          
          <div class="nav-collapse collapse">
            <!-- Navbar Contents -->
          <ul class="nav navbar-nav">
            <li><a href="index.php">Home</a></li>
             <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programs <i class="icon-double-angle-down icon-large"></i></a>
             <ul class="dropdown-menu">
              		  <li><a href="Medical-AssistantXRAY.php"><span>MA w/ Basic X-Ray</span></a></li>
           		  <li><a href="Medical-Assistant-Cardiovascular.php"><span>MA w/ Cardiovascular</span></a></li>
		 		  <li class="divider"></li>
           	       <li><a href="Dental-Assistant.php"><span>Dental Assistant Program</span></a></li>
           	       <li><a href="Dental-Assistant-dental-hygienist.php"><span>Dental Hygienist Info</span></a></li>
           	       <li><a href="continuing-education-for-dental-assistants.php"><span>Dental Assistant (EFDA)</span></a></li>
           	       <li class="divider"></li>
		 		  <li><a href="Cardio-ECHO.php"><span>Tampa ECHO program</span></a></li>
           		  <li><a href="Diagnostic_Cardiovascular_Sonography.php"><span>Orlando ECHO program</span></a></li>
           		  <li><a href="Cardio-CATH.php"><span>Cath Lab Tech</span></a></li>                      
                      <li><a href="Sonographer.php"><span>Sonography</span></a></li>
                      <li><a href="Poly-Technologist.php"><span>Sleep Studies Tech</span></a></li>
                      <li><a href="Surgical-Technologist.php"><span>Surgical Tech</span></a></li>
                      <li><a href="Evenings.php"><span>Evening Classes</span></a></li>
              </ul></li>
              
             <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admissions <i class="icon-double-angle-down icon-large"></i></a>
             <ul class="dropdown-menu">
           	        <li><a href="Admissions.php"><span>How do I enroll?</span></a></li>
           	        <li><a href="financial-aid.php"><span>Financial Aid</span></a></li>
           	        <li><a href="Career-Services.php"class="parent"><span>Career Services</span></a>
		 		   <li><a href="Student-Services.php"><span>Student Services</span></a></li>
               	    <li><a href="pdf/CFI-Catalog.pdf" target="_blank"><span>CFI program catalog</span></a></li>
                      </ul>
                   </li>

             <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">About CFI <i class="icon-double-angle-down icon-large"></i></a>
		   
		   <ul class="dropdown-menu">
			   <li><a href="About-Us.php"><span>About Us</span></a></li>
			   <li><a target="_blank" href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=6000+Cinderlane+Parkway+Orlando,+FL+32810&sll=28.053954,-82.739325&sspn=0.020224,0.045447&ie=UTF8&ll=28.613497,-81.426458&spn=0.010059,0.022724&z=16&iwloc=r0"><span>Orlando School</span></a></li>
        		   <li><a target="_blank" href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=30522+US+Hwy.+19+Suite+300+Palm+Harbor,+FL+34684&ie=UTF8&ll=28.054409,-82.739346&spn=0.010112,0.022724&z=16&iwloc=A&iwd=1&cid=12807723782165198065"><span>Palm Harbor School</span></a></li>
        		   <li><a href="employers.php"><span>Why Hire a CFI grad?</span></a></li>
           	       <li><a href="ghe.php"><span>GHE Partnership</span></a></li>
           	       <li><a href="rasmussen.php"><span>Rasmussen Partnership</span></a></li>
           	       <li><a href="nsu.php"><span>Nova Southeastern</span></a></li>
           	       <li><a href="nlu.php"><span>National Louis University</span></a></li>
        		   <li><a href="Accreditatations.php"><span>CFI Accreditations</span></a></li>
        		</ul></li>
         <li><a href="blog" target="_blank"><span>Blog</span></a></li>
         
         <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bookstore <i class="icon-double-angle-down icon-large"></i></b></a>
		   
		   <ul class="dropdown-menu">
			   <li><a href="https://orlando.cfibookstore.com" target="_blank"><span>Orlando Bookstore</span></a></li>
			   <li><a href="https://palmharbor.cfibookstore.com" target="_blank"><span>Tampa Bay Bookstore</span></a></li>
		   </ul></li>

          </ul>
          <!-- End Navbar Contents -->
              </li>
            </ul>
           
            <ul class="nav navbar-nav pull-right visible-md visible-lg" id="rightNav">
              <li><a href="http://www.facebook.com/pages/Central-Florida-Institute/108791099857" target="_blank"><i class="icon-facebook-sign icon-3x"></i></a></li>
              <li><a href="http://twitter.com/cfiedu" target="_blank"><i class="icon-twitter-sign icon-3x"></i></a></li>
              <li><a href="http://plus.google.com/113698607403845566081?prsrc=3" target="_blank"><i class="icon-google-plus-sign icon-3x"></i></a></li>
              <li><a href="http://www.youtube.com/user/CFISchool" target="_blank"><i class="icon-youtube-sign icon-3x"></i></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
</div>

<!-- Quick Menu -->
     <div class="btn-group btn-group-justified visible-sm visible-xs" id="quickNav">
        <a href="" class="btn btn-warning">Admissions</a>
        <a href="financial-aid.php" class="btn btn-warning">Financial Aid</a>
        <a href="/blog" target="_blank" class="btn btn-warning">Blog</a>
      </div>
      
      			 </div><!-- /.container-->
		</div><!-- / row-->