<div class="list-group" id="quickLinks">
  <a href="#" class="list-group-item active text-center"><h4>Quick Navigation</h4></a>
  <a href="Admissions.php" class="list-group-item">Admissions</a>
  <a href="Student-Services.php" class="list-group-item">Student Services</a>
  <a href="Career-Services.php" class="list-group-item">Career Services</a>
  <a href="financial-aid.php" class="list-group-item">Financial Aid</a>
  <a href="Employers.php" class="list-group-item">CFI Partners</a>
</div>